version: '3.0'
services:
  rasa-nlu-en:
    build:
      context: ./nlu_services/nlu_en
      dockerfile: ../Dockerfile 
    ports:
      - 5005:5005
    healthcheck:
      test: curl --fail http://localhost:5005 || exit 1
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 20s
  rasa-nlu-ru:
    build:
      context: ./nlu_services/nlu_ru
      dockerfile: ../Dockerfile 
    ports:
      - 5006:5005
    healthcheck:
      test: curl --fail http://localhost:5005 || exit 1
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 20s
  dff:
    build: ./dff
    ports:
      - 8080:80
      - 5678:5678
    command: [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn server:app --host 0.0.0.0 --port 80"
      ]
    depends_on:
      rasa-nlu-en:
        condition: service_healthy
      rasa-nlu-ru:
        condition: service_healthy
